## Indexer Cluster Configuration
---
- name: Configure Splunk Infrastructure
  hosts: clustermanager
  gather_facts: false
  become: yes
  become_user: splunk_user

  tasks:
    - name: Copy Cluster Manager Config
      copy:
        src: ./indexer_clustering/cluster_manager_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644
      register: copy_task

    - name: Restart Splunk
      shell: sudo systemctl restart Splunkd
      when: copy_task.changed

      # ansible.builtin.systemd:
      #   state: restarted
      #   name: Splunkd

- name: Configure Splunk Infrastructure - Indexers
  hosts: indexers
  gather_facts: false
  become: yes
  become_user: splunk_user

  tasks:
    - name: Copy Config to Indexers
      copy:
        src: ./indexer_clustering/indexer_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644
      register: copy_task

    - name: Restart Splunk
      shell: sudo systemctl restart Splunkd
      when: copy_task.changed

- name: Configure Splunk Infrastructure - Search Heads
  hosts: searchheads
  gather_facts: false
  become: yes
  become_user: splunk_user

  tasks:
    - name: Copy Config to Search Heads
      copy:
        src: ./indexer_clustering/searchhead_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644
      register: copy_task

    - name: Restart Splunk
      shell: sudo systemctl restart Splunkd
      when: copy_task.changed

### Cluster Manager manager-apps directory Deployment
- name: Configure Splunk Infrastructure
  hosts: clustermanager
  gather_facts: false
  become: yes
  become_user: splunk_user

  tasks:
    - name: Copy Inputs Config to Cluster Manager manager-apps directory
      copy:
        src: ./indexer_clustering/idx_inputs_addon
        dest: /opt/splunk/etc/manager-apps
        owner: splunk_user
        group: splunk_user
        mode: 0644
      register: copy_task

    - name: Apply Cluster Bundle Push
      shell: /opt/splunk/bin/splunk apply cluster-bundle -auth admin:P@ssword123
      when: copy_task.changed

### Search Head Cluster Configuration
- name: Configure Splunk Infrastructure
  hosts: deployer
  gather_facts: false
  become: yes
  become_user: splunk_user

  tasks:
    - name: Copy SH Cluster Config to the Deployer
      copy:
        src: ./searchhead_clustering/deployer_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644
      register: copy_task

    - name: Restart Splunk
      shell: sudo systemctl restart Splunkd
      when: copy_task.changed

- name: Copy SH Cluster Config to the Search Heads
  hosts: searchheads
  become: yes
  become_user: splunk_user
  vars:
    deployer: "{{ groups['deployer'][0] }}"

  tasks:
    - name: Copy SH Cluster Config - Search Heads
      copy:
        src: ./searchhead_clustering/sh_cluster_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644
      # run only on the first search head
      # when: inventory_hostname == groups['searchheads'][0]
      register: copy_task

    - name: Set mgmt_uri in server.conf
      lineinfile:
        path: /opt/splunk/etc/apps/sh_cluster_addon/local/server.conf
        regexp: '^mgmt_uri\s*=.*$'
        line: "mgmt_uri = https://{{ ansible_facts['hostname'] }}:8089"

    - name: Set conf_deploy_fetch_url in server.conf
      lineinfile:
        path: /opt/splunk/etc/apps/sh_cluster_addon/local/server.conf
        regexp: '^conf_deploy_fetch_url\s*=.*$'
        line: "conf_deploy_fetch_url = https://{{ deployer }}:8089"

    - name: Ensure splunk_user owns mgmt_uri file
      file:
        path: /opt/splunk/
        owner: splunk_user
        group: splunk_user

    - name: Enable web.conf SSL on all SHs - Search Heads
      copy:
        src: ./searchhead_clustering/web_ssl_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644
      register: copy_task

    - name: Restart Splunk
      shell: sudo systemctl restart Splunkd
      when: copy_task.changed

    - name: Wait for Splunk to restart
      wait_for:
        port: 8000
        delay: 10
        timeout: 300

    - name: Assign SH Cluster Captain
      # get the list of search heads from the inventory and join them with a comma
      # this will be the list of search heads to join the cluster
      shell: /opt/splunk/bin/splunk bootstrap shcluster-captain -servers_list "{{ groups['searchheads'] | map('regex_replace', '^', 'https://') | map('regex_replace', '$', ':8089') | join(',') }}" -auth admin:P@ssword123

      # run only on the first search head
      when: inventory_hostname == groups['searchheads'][0] and copy_task.changed

### Search Head Cluster Deployer Push
- name: Deploy Outputs to Search Heads - Deployer
  hosts: deployer
  become: yes
  become_user: splunk_user

  tasks:
    - name: Copy SH Cluster Config - Deployer
      copy:
        src: ./outputs_addon
        dest: /opt/splunk/etc/shcluster/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Modify outputs.conf to include all indexers, find and replace server =
      replace:
        path: /opt/splunk/etc/shcluster/apps/outputs_addon/default/outputs.conf
        regexp: "server = .*"
        replace: "server = {{ groups['indexers'] | map('regex_replace', '$', ':9997') | join(',') }}"

    # - name: Push SH Cluster Config
    #   shell: /opt/splunk/bin/splunk apply shcluster-bundle -target https://{{ groups['searchheads'][0] }}:8089 -auth admin:P@ssword123 --preserve-lookups true --answer-yes

## Configure Universal Forwarders
- name: Configure Universal Forwarders
  hosts: universalforwarder
  become: yes
  become_user: splunk_user
  tasks:
    - name: Copy ServerClass Config - Deployment Server
      copy:
        src: ./TA_deploymentclient
        dest: /opt/splunkforwarder/etc/apps
        # owner: splunk_user
        # group: splunk_user
        # mode: 0644
    - name: Modify deploymentclient to include the deployment server, find and replace targetUri =
      replace:
        path: /opt/splunkforwarder/etc/apps/TA_deploymentclient/default/deploymentclient.conf
        regexp: "targetUri = .*"
        replace: "targetUri = {{ groups['deploymentserver'] | map('regex_replace', '^', 'https://') | map('regex_replace', '$', ':8089') | join(',') }}"
    - name: Restart Splunk
      shell: /opt/splunkforwarder/bin/splunk restart

## Deploy Outputs to Univesal Forwarder - Deployment Server
- name: Deploy Outputs to Univesal Forwarder - Deployment Server
  hosts: deploymentserver
  become: yes
  become_user: splunk_user

  tasks:
    - name: Copy ServerClass Config - Deployment Server
      copy:
        src: ./serverclass_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Copy Outputs Config - Deployment Server deployment-apps directory
      copy:
        src: ./outputs_addon
        dest: /opt/splunk/etc/deployment-apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Modify outputs.conf to include all indexers, find and replace server =
      replace:
        path: /opt/splunk/etc/deployment-apps/outputs_addon/default/outputs.conf
        regexp: "server = .*"
        replace: "server = {{ groups['indexers'] | map('regex_replace', '$', ':9997') | join(',') }}"

    - name: Apply Deployment Server Bundle Push
      shell: /opt/splunk/bin/splunk reload deploy-server -auth admin:P@ssword123

## Deploy Outputs to all other servers excluding indexers, searchheads, universal forwarders
- name: Deploy Outputs to all other servers excluding indexers, searchheads, universal forwarders
  hosts: all:!indexers:!universalforwarder #:!searchheads
  become: yes
  become_user: splunk_user

  tasks:
    - name: Copy Outputs Config - All Server
      copy:
        src: ./outputs_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Modify outputs.conf to include all indexers, find and replace server =
      replace:
        path: /opt/splunk/etc/apps/outputs_addon/default/outputs.conf
        regexp: "server = .*"
        replace: "server = {{ groups['indexers'] | map('regex_replace', '$', ':9997') | join(',') }}"

    - name: Restart Splunkd
      shell: sudo systemctl restart Splunkd
