## Indexer Cluster Configuration
---
- name: Configure Splunk Infrastructure - Cluster Manager
  hosts: clustermanager
  gather_facts: false
  become: yes
  become_user: splunk_user

  tasks:
    - name: Get Cluster Manager public IP from external service
      shell: curl -s http://icanhazip.com
      register: clustermanager_public_ip
      delegate_to: "{{ groups['clustermanager'][0] }}"

    - name: Set clustermanager_public_ip fact
      set_fact:
        clustermanager_public_ip: "{{ clustermanager_public_ip.stdout }}"

    - name: Copy Cluster Manager Config
      copy:
        src: ./indexer_clustering/cluster_manager_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Restart Splunk
      shell: sudo systemctl restart Splunkd

    - name: Wait for Splunk to start on {{ inventory_hostname }}
      wait_for:
        port: 8089
        delay: 10
        timeout: 300

- name: Configure Splunk Infrastructure - Indexers
  hosts: indexers
  gather_facts: false
  become: yes
  become_user: splunk_user
  vars:
    clustermanager: "{{ groups['clustermanager'][0] }}"

  tasks:
    - name: Get Indexers public IP from external service
      shell: curl -s http://icanhazip.com
      register: indexer_public_ip
      delegate_to: "{{ inventory_hostname }}"

    - name: Set indexer_public_ip fact as a list
      set_fact:
        indexer_public_ip: "{{ indexer_public_ip.stdout }}"

    - name: Show indexer_public_ip fact
      debug:
        var: indexer_public_ip

    - name: Copy Indexers Configs
      copy:
        src: ./indexer_clustering/indexer_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Set manager_uri in server.conf
      lineinfile:
        path: /opt/splunk/etc/apps/indexer_addon/local/server.conf
        regexp: '^manager_uri\s*=.*$'
        line: "manager_uri = https://{{ hostvars[groups['clustermanager'][0]].clustermanager_public_ip }}:8089"

    - name: Ensure splunk_user owns /opt/splunk/ directory
      file:
        path: /opt/splunk/
        owner: splunk_user
        group: splunk_user
        recurse: yes

    - name: Restart Splunk
      shell: sudo systemctl restart Splunkd

    - name: Wait for Splunk to start on {{ inventory_hostname }}
      wait_for:
        port: 8089
        delay: 10
        timeout: 300
      ignore_errors: yes

- name: Configure Splunk Infrastructure - Search Heads
  hosts: searchheads
  gather_facts: false
  become: yes
  become_user: splunk_user
  vars:
    clustermanager: "{{ groups['clustermanager'][0] }}"

  tasks:
    - name: Copy Search Heads Configs
      copy:
        src: ./indexer_clustering/searchhead_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Set manager_uri in server.conf
      lineinfile:
        path: /opt/splunk/etc/apps/searchhead_addon/local/server.conf
        regexp: '^manager_uri\s*=.*$'
        line: "manager_uri = https://{{ hostvars[groups['clustermanager'][0]].clustermanager_public_ip }}:8089"

    - name: Restart Splunk
      shell: sudo systemctl restart Splunkd

### Cluster Manager manager-apps directory Deployment
- name: Configure Splunk Infrastructure
  hosts: clustermanager
  gather_facts: false
  become: yes
  become_user: splunk_user

  tasks:
    - name: Copy Inputs Config to Cluster Manager manager-apps directory
      copy:
        src: ./indexer_clustering/idx_inputs_addon
        dest: /opt/splunk/etc/manager-apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Apply Cluster Bundle Push
      shell: /opt/splunk/bin/splunk apply cluster-bundle -auth admin:P@ssword123

### Search Head Cluster Configuration
- name: Configure Splunk Infrastructure - Search Head Cluster Deployer
  hosts: deployer
  gather_facts: false
  become: yes
  become_user: splunk_user

  tasks:
    - name: Get public IP from external service
      shell: curl -s http://icanhazip.com
      register: deployer_public_ip
      delegate_to: "{{ groups['deployer'][0] }}"

    - name: Set deployer_public_ip fact
      set_fact:
        deployer_public_ip: "{{ deployer_public_ip.stdout }}"

    - name: Copy SH Cluster Config to the Deployer
      copy:
        src: ./searchhead_clustering/deployer_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Restart Splunk
      shell: sudo systemctl restart Splunkd

    - name: Wait for Splunk to start on {{ inventory_hostname }}
      wait_for:
        port: 8089
        delay: 10
        timeout: 300

- name: Copy SH Cluster Config to the Search Heads
  hosts: searchheads
  become: yes
  become_user: splunk_user
  vars:
    deployer: "{{ groups['deployer'][0] }}"

  tasks:
    - name: Copy SH Cluster Config - Search Heads
      copy:
        src: ./searchhead_clustering/sh_cluster_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Get public IP from external service
      shell: curl -s http://icanhazip.com
      register: searchhead_public_ip
      delegate_to: "{{ inventory_hostname }}"

    - name: Set searchhead_public_ip fact
      set_fact:
        searchhead_public_ip: "{{ searchhead_public_ip.stdout }}"

    - name: Set mgmt_uri in server.conf
      lineinfile:
        path: /opt/splunk/etc/apps/sh_cluster_addon/local/server.conf
        regexp: '^mgmt_uri\s*=.*$'
        line: "mgmt_uri = https://{{ searchhead_public_ip }}:8089"

    - name: Set conf_deploy_fetch_url in server.conf
      lineinfile:
        path: /opt/splunk/etc/apps/sh_cluster_addon/local/server.conf
        regexp: '^conf_deploy_fetch_url\s*=.*$'
        line: "conf_deploy_fetch_url = https://{{ hostvars[groups['deployer'][0]].deployer_public_ip  }}:8089"

    - name: Ensure splunk_user owns /opt/splunk/ directory
      file:
        path: /opt/splunk/
        owner: splunk_user
        group: splunk_user
        recurse: yes

    - name: Enable web.conf SSL on all SHs - Search Heads
      copy:
        src: ./searchhead_clustering/web_ssl_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Restart Splunk
      shell: sudo systemctl restart Splunkd

    - name: Wait for Splunk to start on {{ inventory_hostname }}
      wait_for:
        port: 8089
        delay: 10
        timeout: 300

    - name: Assign SH Cluster Captain
      shell: /opt/splunk/bin/splunk bootstrap shcluster-captain -servers_list "{{ groups['searchhead'] | map('extract', hostvars, 'searchhead_public_ip') | map('regex_replace', '^', 'https://') | map('regex_replace', '$', ':8089') | join(',') }}" -auth admin:P@ssword123
      # run only on the first search head
      when: inventory_hostname == groups['searchheads'][0]
      register: bootstrap_task
      ignore_errors: yes

    - name: If Assign SH Cluster Captain Fails, Stop Splunk on all SHs
      shell: sudo systemctl stop Splunkd
      when: bootstrap_task is failed

    - name: If Assign SH Cluster Captain Fails, do a clean raft
      shell: /opt/splunk/bin/splunk clean raft -auth admin:P@ssword123 --answer-yes
      when: inventory_hostname == groups['searchheads'][0] and bootstrap_task is failed

    - name: Start Splunk on all SHs after Clean Raft
      shell: sudo systemctl start Splunkd
      when: bootstrap_task is failed and inventory_hostname == groups['searchheads']

    - name: Assign SH Cluster Captain after Clean Raft
      shell: /opt/splunk/bin/splunk bootstrap shcluster-captain -servers_list "{{ groups['searchhead'] | map('extract', hostvars, 'searchhead_public_ip') | map('regex_replace', '^', 'https://') | map('regex_replace', '$', ':8089') | join(',') }}" -auth admin:P@ssword123
      # run only on the first search head
      when: inventory_hostname == groups['searchheads'][0] and bootstrap_task is failed
      ignore_errors: yes

### Search Head Cluster Deployer Push
- name: Deploy Outputs Configs to Search Heads - From Deployer
  hosts: deployer
  become: yes
  become_user: splunk_user

  tasks:
    - name: Copy Outputs Config to Deployer SHCLUSTER/APPS
      copy:
        src: ./outputs_addon
        dest: /opt/splunk/etc/shcluster/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Modify outputs.conf to include all indexers
      replace:
        path: /opt/splunk/etc/shcluster/apps/outputs_addon/local/outputs.conf
        regexp: "server = .*"
        replace: "server = {{ groups['indexers'] | map('extract', hostvars, 'indexer_public_ip') | map('regex_replace', '$', ':9997') | join(',') }}"

    - name: Push Outputs Cluster Config to Search Heads
      shell: /opt/splunk/bin/splunk apply shcluster-bundle -target https://{{ hostvars[groups['searchheads'][0]]['searchhead_public_ip'] }}:8089 -auth admin:P@ssword123 --preserve-lookups true --answer-yes

      ignore_errors: yes

## Configure Universal Forwarders
- name: Configure Universal Forwarders
  hosts: universalforwarder
  become: yes
  become_user: splunk_user
  tasks:
    - name: Copy DeploymentClient Config to Universal Forwarder
      copy:
        src: ./TA_deploymentclient
        dest: /opt/splunkforwarder/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Modify deploymentclient to include the Deployment Server
      replace:
        path: /opt/splunkforwarder/etc/apps/TA_deploymentclient/local/deploymentclient.conf
        regexp: "targetUri = .*"
        replace: "targetUri = {{ groups['deploymentserver'] | map('regex_replace', '^', 'https://') | map('regex_replace', '$', ':8089') | join(',') }}"

    # - name: Ensure splunk_user owns /opt/splunkforwarder/ directory
    #   file:
    #     path: /opt/splunkforwarder/
    #     owner: splunk_user
    #     group: splunk_user
    #     recurse: yes

    - name: Restart Splunk
      shell: /opt/splunkforwarder/bin/splunk restart

## Deploy Outputs to Univesal Forwarder - Deployment Server
- name: Deploy Outputs to Univesal Forwarder - From Deployment Server DEPLOYMENT-APPS directory
  hosts: deploymentserver
  become: yes
  become_user: splunk_user

  tasks:
    - name: Copy ServerClass Config - Deployment Server
      copy:
        src: ./serverclass_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Copy Outputs Config - Deployment Server deployment-apps directory
      copy:
        src: ./outputs_addon
        dest: /opt/splunk/etc/deployment-apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Modify outputs.conf to include all indexers
      replace:
        path: /opt/splunk/etc/deployment-apps/outputs_addon/local/outputs.conf
        regexp: "server = .*"
        replace: "server = {{ groups['indexers'] | map('extract', hostvars, 'indexer_public_ip') | map('regex_replace', '$', ':9997') | join(',') }}"

    - name: Apply Deployment Server Bundle Push
      shell: /opt/splunk/bin/splunk reload deploy-server -auth admin:P@ssword123

## Deploy Outputs to all other servers excluding indexers, searchheads, universal forwarders
- name: Deploy Outputs to all other servers excluding indexers, searchheads, universal forwarders
  hosts: all:!indexers:!universalforwarder #:!searchheads
  become: yes
  become_user: splunk_user

  tasks:
    - name: Copy Outputs Config - To all Server
      copy:
        src: ./outputs_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Modify outputs.conf to include all indexers
      replace:
        path: /opt/splunk/etc/apps/outputs_addon/local/outputs.conf
        regexp: "server = .*"
        replace: "server = {{ groups['indexers'] | map('extract', hostvars, 'indexer_public_ip') | map('regex_replace', '$', ':9997') | join(',') }}"
# - name: Delete file server.conf on all other servers excluding universal forwarders
#   hosts: all:!universalforwarder
#   become: yes
#   become_user: splunk_user

#   tasks:
#     - name: Delete the server.conf in /opt/splunk/etc/system/local
#       file:
#         path: /opt/splunk/etc/system/local/server.conf
#         state: absent

#     - name: Stop Splunkd
#       shell: sudo systemctl stop Splunkd

#     - name: Start Splunkd
#       shell: sudo systemctl start Splunkd

#     - name: Wait for Splunk to start
#       wait_for:
#         port: 8089
#         delay: 10
#         timeout: 300
