## Indexer Cluster Configuration
---
- name: Configure Splunk Infrastructure
  hosts: clustermanager
  gather_facts: false
  become: yes
  become_user: splunk_user

  tasks:
    - name: Copy Cluster Manager Config
      copy:
        src: ./indexer_clustering/cluster_manager_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Restart Splunk
      shell: sudo systemctl restart Splunkd

      # ansible.builtin.systemd:
      #   state: restarted
      #   name: Splunkd

- name: Configure Splunk Infrastructure - Indexers
  hosts: indexers
  gather_facts: false
  become: yes
  become_user: splunk_user

  tasks:
    - name: Copy Config to Indexers
      copy:
        src: ./indexer_clustering/indexer_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Restart Splunk
      shell: sudo systemctl restart Splunkd

- name: Configure Splunk Infrastructure - Search Heads
  hosts: searchheads
  gather_facts: false
  become: yes
  become_user: splunk_user

  tasks:
    - name: Copy Config to Search Heads
      copy:
        src: ./indexer_clustering/searchhead_addon
        dest: /opt/splunk/etc/apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Restart Splunk
      shell: sudo systemctl restart Splunkd

### Cluster Manager manager-apps directory Deployment
- name: Configure Splunk Infrastructure
  hosts: clustermanager
  gather_facts: false
  become: yes
  become_user: splunk_user

  tasks:
    - name: Copy Inputs Config to Cluster Manager manager-apps directory
      copy:
        src: ./indexer_clustering/idx_inputs_addon
        dest: /opt/splunk/etc/manager-apps
        owner: splunk_user
        group: splunk_user
        mode: 0644

    - name: Apply Cluster Bundle Push
      shell: /opt/splunk/bin/splunk apply cluster-bundle -auth admin:P@ssword123
